package com.company.saga.order.saga;

public enum SagaStep {
    ORDER_CREATED,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    INVENTORY_RESERVING,
    INVENTORY_RESERVED,
    SHIPPING_CREATING,
    COMPLETED,
    PAYMENT_FAILED,
    INVENTORY_FAILED,
    SHIPPING_FAILED,
    COMPENSATION_STARTED,
    CANCELLED
}
